<?

class SettingsConstants {

  public static $SETTINGS_KEYS = array(
    'LANGUAGE',
    'TIME_ZONE',
    'ENCODING',
    'ABSOLUTE_URL',
    'ADMIN_EMAIL',
    'AUTO_LOGIN_USER_ID',
    'DEFAULT_USER_ID',
    'PASSWORD',
    'DB_SERVER',
    'DB_USER',
    'DB_PASSWORD',
    'DB_DATABASE',
    'DB_TABLE_PREFIX',
    'METRIC_UNITS',
    'DATE_FORMAT',
    'DATE_FORMAT_WITHOUT_YEAR',
    'DATE_TIME_FORMAT',
    'DATE_TIME_FORMAT_SECONDS',
    'DATE_TIME_FORMAT_WITHOUT_YEAR',
    'DECIMAL_DELIMITER',
    'THOUSANDS_DELIMITER',
    'GPX_DIR',
    'LIMIT_FOR_DETMINING_LOADED_GPX_FILES',
    'PHOTO_THUMBNAIL_PREFIX',
    'PHOTO_THUMBNAIL_WIDTH',
    'PHOTO_THUMBNAIL_HEIGHT',
    'PHOTO_RATING_MIN',
    'PHOTO_RATING_MAX',
    'PHOTO_RATING_DEFAULT',
    'LEAFLET_MAP_TILES',
    'MAX_EXTERNAL_ACTIVITIES_TO_FETCH',
    'ACTIVITY_SELECTION_TIME_TOLERANCE',
    'MIN_YEAR',
    'EMPTY_VALUE_FOR_SELECT_BOX',
    'USE_LOCATION_SERVICE_TO_FILL_DATA',
    'LOCATION_SERVICE_LANGUAGE',
    'LOCATION_SERVICE_URL',
    'GET_WEATHER_DATA_FROM_DESCRIPTION',
  );

}

?>
